#ifndef LWIPOPTS_H
#define LWIPOPTS_H

#define NO_SYS 0
#define LWIP_SOCKET 1
#define LWIP_NETCONN 1
#define LWIP_NETIF_API 1
#define LWIP_TCPIP_CORE_LOCKING 1
#define SYS_LIGHTWEIGHT_PROT 1

#define MEM_ALIGNMENT 4
#define MEM_SIZE (16 * 1024)
#define MEMP_NUM_PBUF 16
#define MEMP_NUM_TCP_PCB 8
#define MEMP_NUM_TCP_PCB_LISTEN 8
#define MEMP_NUM_TCP_SEG 32
#define MEMP_NUM_SYS_TIMEOUT 16
#define MEMP_NUM_NETBUF 8
#define MEMP_NUM_NETCONN 16
#define MEMP_NUM_TCPIP_MSG_API 16
#define MEMP_NUM_TCPIP_MSG_INPKT 16
#define PBUF_POOL_SIZE 24

#define LWIP_ARP 1
#define LWIP_ETHERNET 1
#define LWIP_ICMP 1
#define LWIP_RAW 1
#define LWIP_DHCP 1
#define LWIP_DNS 1
#define LWIP_UDP 1
#define LWIP_TCP 1
#define TCP_TTL 255
#define UDP_TTL 255
#define TCP_LISTEN_BACKLOG 1
#define TCP_QUEUE_OOSEQ 1
#define TCP_MSS 1460
#define TCP_SND_BUF (8 * TCP_MSS)
#define TCP_SND_QUEUELEN ((4 * TCP_SND_BUF + TCP_MSS - 1) / TCP_MSS)
#define TCP_WND (8 * TCP_MSS)
#define LWIP_NETIF_STATUS_CALLBACK 1
#define LWIP_NETIF_LINK_CALLBACK 1
#define LWIP_SO_RCVTIMEO 1
#define LWIP_SO_SNDTIMEO 1
#define LWIP_TIMEVAL_PRIVATE 0
#define LWIP_SO_RCVBUF 1
#define LWIP_COMPAT_SOCKETS 0
#define LWIP_POSIX_SOCKETS_IO_NAMES 0
#define LWIP_SOCKET_OFFSET 0
#define LWIP_PROVIDE_ERRNO 1

/* Mailbox sizes - REQUIRED for FreeRTOS sys_arch (size must be > 0) */
#define TCPIP_MBOX_SIZE              16
#define DEFAULT_TCP_RECVMBOX_SIZE    16
#define DEFAULT_UDP_RECVMBOX_SIZE    16
#define DEFAULT_RAW_RECVMBOX_SIZE    16
#define DEFAULT_ACCEPTMBOX_SIZE       8
#define TCPIP_THREAD_STACKSIZE      1024
#define TCPIP_THREAD_PRIO             3

#define LWIP_ASSERT_CORE_LOCKED()

#endif
